### ISSUE TITLE
Suggestion: add the ability to search for files for a specific extension

### ISSUE THREAD

**Issue by NataliaBondarenko** [victordomingos/Count-files#2]
Hello, Victor Domingos!
Something like this.
countfiles.py
import:
```
from pathlib import Path
```
in class  WordCounter:
```
    def get_files_by_extension(self, args_path: str, args_fe: str):
        """This is like calling Path.glob() with '**' added in front of the given pattern
        The '**' pattern means 'this directory and all subdirectories, recursively'.
        In other words, it enables recursive globbing.
        (including folder name or filename with dot)
        :param args_path: path to file, args.path
        :param args_fe: file extension, args.fe
        :return:
        """
        print('path: ', os.path.expanduser(args_path))
        print('extension: ', args_fe)
        files = sorted(Path(os.path.expanduser(args_path)).rglob(f"*.{args_fe}"))
        print('len files: ', len(files))
        if files:
            for el in files:
                print('path: ', el)
                print('size: ', el.stat().st_size)
                print('text: ', el.read_text()[0:200].replace('\n', ' '))
        return

# Path.stat().st_size return information about this path (similarly to os.stat())
# Size of the file in bytes, if it is a regular file or a symbolic link.
# The size of a symbolic link is the length of the pathname it contains,
# without a terminating null byte.
# Depending on the extension: Path.read_text() may not work
# Path.read_text(), this makes sense if there is module-level docstrings
```
to ArgumentParser:
```
parser.add_argument('-fe', required=False, choices=('py', 'html'),
                                   type=str, help='find files by extension')
```
in flow control:
```
if args.fe:
    fc.get_files_by_extension(args.path, args.fe)
```

**Comment by victordomingos** [comment]
It’s a nice feature we can add. Thanks for the suggestion. I will try to add it to soon.

I am not sure about the `read_text()` part, maybe it deserves to become a separate option, like `--preview`, as it would allow to display a more compact view by default (just with file size and file path). I just need to see how it fits the current command line arguments scheme, where everything is intentionally optional. I will definitely think about it :)

Other thing that I am still not sure about is if we should really provide a list of choices to the `-fe` argument. It limits functionality, so probably it’s a better idea to allow the user to search by any file extension he/she wants.

**Comment by NataliaBondarenko** [comment]
If the purpose of the utility is to collect statistics, then ```read_text()``` is not necessary.
Change, for example, to ```el.stat().st_mtime```  (Time of most recent content modification expressed in seconds).
Python has the ability to interact with the OS. In which cases can such statistics be useful?

Maybe without a list of choices. If a list of choices is specified, then the parser automatically checks the correctness of user input (you do not need to do it yourself).
Will you only use the Python Standard Library?
(without external dependencies)

**Comment by victordomingos** [comment]
The main idea with this application is simply counting files by file extension, for instance to get an idea of what's in a project folder (in my case, I wanted simply to know how many image and HTML files Pelican generated behind the scenes while building the website, out of pure curiosity), but i can see how it could be useful to have a way to display a content preview for text-based files. In my opinion, the preview should be optional, i.e. the user should be able to count files (or even display their paths), without the file preview. We could then have `-fe` (find by extension) and `--preview`(show a little preview for text files). 

Regarding the list of choices for extensions, that can be limiting, because in Unix world, and for developers in general, there isn't really a fixed, universal, set of file extensions. While I understand it could be useful to have that additional validation of user input, I am afraid it may reduce functionality by offering less options that those the user may want to use.

For this project, I prefer to use only the Standard Library if possible, but in case there is a good reason to use any external package, I am open to that, as long it is pure-python and can be installed and run on Pythonista for iOS.

**Comment by victordomingos** [comment]
I have started to merge your suggestion with my code, you may check it out in the repo. I will need to take a closer look, because the read_text() seems to be returning an error on some files (probably non-text files).

**Comment by victordomingos** [comment]
Just a quick notice to let you know that I have just released a new version. Made a few changes in the code, for instance to allow the customization of preview sample text, and to solve that error. Please take a look and let me know if you have any suggestions or in case you find any bug.
