### ISSUE TITLE
Add a new option to count only files with a given extension, but without listing them.

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#38]
Similar to `countfiles -fe`, but without actually listing any files, just displaying the stats.

E.g.:

```
count files -fe txt -nl DIRPATH
countfiles --file-extension -no-list DIRPATH
```

Sample Output:
```
$count files -fe txt -nl ~/Desktop

Recursively counting all files with extension .txt, ignoring hidden files and directories, in /Users/Username/Desktop

   Found 37 file(s).
   Total combined size: 93.2 KiB.
   Average file size: 2.5 KiB (max: 6.0 KiB, min: 109.0 B).

$
```

**Comment by NataliaBondarenko** [comment]
Yes, the list can be very long if there are many files.
If I understand your proposal correctly, the visualization for the user will be:
1. table/no table (available for all extensions)
2. list/no list (available for search for extension)
3. preview (available for search for extension)
- table:
  - sort alpha
  - sort freq (default)

- no table:
  - total number

- list:
  - list with paths and sizes

- no list:
  - total number and sizes

- preview
  - file content

A list or table can be large.
It might be advisable to output the data to a text file, rather than to a screen. Users can then analyze them according to their tasks.
What do you think?

With the preview, not everything is clear. It works, but the result for the media files is not very informative.
Query with preview:
```
Recursively searching all files with extension .jpg, ignoring hidden files and directories, in C:\Users\Net/Desktop/providers
```
Result for jpg:
```
C:\Users\Net/Desktop/providers\Новая папка\DD Weather Icon Set 65500\clear.jpg (20.7 KiB)
–––––––––––––––––––––––––––––––––––
.jpg  JPEG|EXIF|SPIFF images 0.9
яШяа ►JFIF ☺☺☺ H H  яб◄,Exif  MM *  ♣☺↕ ♥   ☺ ☺  ☺1 ☻   ↔V☺2 ☻   ¶t‡i ♦   ☺€к∟  ♀   J    ∟к


–––––––––––––––––––––––––––––––––––
```
It is probably worth to show previews for text files and check their size or read line by line.

**Comment by victordomingos** [comment]
> Yes, the list can be very long if there are many files.
> If I understand your proposal correctly, the visualization for the user will be:
> 1. table/no table (available for all extensions)
> 2. list/no list (available for search for extension)
> 3. preview (available for search for extension)

We have currently two kinds of list output, one for file counting (an extensions table), another for file searching (a file path list). This file path list can optionally include a file preview. 

So, it would be like this:
  

**A) File counting by extension**
 - table (listing file extension frequencies) - enabled by default
    - Sort alphabetically
    - Sort by frequency - enabled by default
 - no table (just a summary) 

**B) File searching by extension**
 - list of all found file paths - enabled by default
    - Optional file preview - not enabled by default
        - Optional size specification for file preview 
 - no list (just a summary)

Maybe it would make sense to change the summary in *A)* to show the same set of file stats as the summary in *B)*.

**Comment by victordomingos** [comment]
In that case, we can add a generic preview procedure that say something like `[No preview available for this file type.]`. If there is no compatible preview routine, that message gets printed instead.

**Comment by NataliaBondarenko** [comment]
main.py
allowed = ('txt', 'py', 'html', ....)
if args.file_extension and args.preview:
    if args.file_extension  not in allowed:
        print(f'No preview available for this file type. Allowed types {allowed}')
        return
